### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by nickoneill** [nickoneill/PermissionScope#43]
Some things we have to do for a stable API release:
- [x] Bluetooth support (#40)
- [x] CoreMotion support (#53)
- [x] Solidify API for non-UI requests (#39)
- [ ] Fix Request methods (#125 and #130)

Removed:
- [ ] Automated testing in place (#45)
- [ ] Fix deallocated instance error (#30)

This list is not exhaustive, just a start.

**Comment by bre7** [comment]
And fix #30

**Comment by bre7** [comment]
The following permissions should probably be in the next version since they require important changes to the API:
- [x] HealthKit support
- [ ] CloudKit support

**Comment by nickoneill** [comment]
Yep, I'll jump on one of these threads and see what's happening with the async request stuff in the next day or two.
